name: python-udemy

on:
  push:
    paths-ignore:
      - doc/**
      - README.md
    branches:
      - main
      - dev-test
  pull_request:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-20.04
    steps:
      - run: DATE=$(date) >> $GITHUB ENV
      - run: echo "$DATE"

  
